'use strict';
const express = require('express');
const router = express.Router();

router.get('/sessions', (req, res) => res.json({ total: 2, page: 1, pageSize: 20, items: [
  { sessionKey: 'demo-session-1', harness: 'codex', requestCount: 8, totalTokens: 128000, totalCachedTokens: 32000, firstSeen: new Date(Date.now() - 86400000).toISOString(), lastSeen: new Date().toISOString(), cwd: '/workspace/crewrouter', lastMessagePreview: '分析项目架构并生成改进建议', toolCallCount: 12, pressureLevel: 'ok' },
  { sessionKey: 'demo-session-2', harness: 'claude_code', requestCount: 5, totalTokens: 86000, totalCachedTokens: 18000, firstSeen: new Date(Date.now() - 2 * 86400000).toISOString(), lastSeen: new Date(Date.now() - 3600000).toISOString(), cwd: '/workspace/plugin-lab', lastMessagePreview: '检查插件商店数据展示', toolCallCount: 7, pressureLevel: 'warning' },
]}));
router.get('/sessions/search', (req, res) => res.json({ totalSessions: 1, results: [{ sessionKey: 'demo-session-1', harness: 'codex', firstSeen: new Date(Date.now() - 86400000).toISOString(), lastSeen: new Date().toISOString(), matchCount: 2, previews: [{ ts: new Date().toISOString(), excerpt: '<<<MARK>>>演示<<<END>>> 项目架构分析' }] }] }));
router.get('/sessions/:key/messages', (req, res) => res.json({ total: 2, page: 1, pageSize: 40, hasMore: false, records: [{ id: 1, ts: new Date(Date.now() - 3600000).toISOString(), model: 'gpt-4.1', harness: 'codex', tokens: 64000, cachedTokens: 16000, events: [{ type: 'text', role: 'user', text: '请分析演示项目结构。' }, { type: 'thinking', preview: '整理目录与依赖关系。' }, { type: 'text', role: 'assistant', text: '项目包含控制台、管理后台和插件商店。' }] }, { id: 2, ts: new Date().toISOString(), model: 'gpt-4.1', harness: 'codex', tokens: 64000, cachedTokens: 16000, events: [{ type: 'tool_call', name: 'read_file', argsPreview: 'README.md' }, { type: 'tool_result', name: 'read_file', resultPreview: '演示文件内容' }] }] }));
router.get('/custom-instructions', (req, res) => res.json({ total: 2, page: 1, pageSize: 20, scan_window_days: 30, scan_max_records: 1000, scope: 'self', items: [{ fingerprint: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', file: 'AGENTS.md', source: 'project', chars: 420, occurrence_count: 18, first_seen: new Date(Date.now() - 86400000).toISOString(), last_seen: new Date().toISOString(), truncated: false, positions: ['system'], sample_record_id: 1, preview: '保持改动小而清晰，先验证再提交。' }, { fingerprint: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', file: 'CLAUDE.md', source: 'user', chars: 210, occurrence_count: 9, first_seen: new Date(Date.now() - 3 * 86400000).toISOString(), last_seen: new Date(Date.now() - 3600000).toISOString(), truncated: false, positions: ['system'], sample_record_id: 2, preview: '使用简体中文回复用户。' }] }));
router.get('/inject-prompts', (req, res) => res.json({ items: [{ id: 1, name: '演示编码规范', content: '请保持代码简洁，并在修改后运行验证。', enabled: true, sort_order: 0, bound_key_ids: [1], bound_keys: [{ id: 1, name: '生产环境 Key' }] }] }));
router.get('/inject-prompts/my-keys', (req, res) => res.json({ items: [{ id: 1, name: '生产环境 Key', key_prefix: 'sk-demo-prod' }, { id: 2, name: '测试环境 Key', key_prefix: 'sk-demo-test' }] }));
router.get('/notifications', (req, res) => res.json([{ id: 1, type: 'usage', title: '演示通知', message: '今日已完成 128 次模型调用。', is_read: false, created_at: new Date(Date.now() - 3600000).toISOString() }]));
router.get('/notification-settings', (req, res) => res.json({ barkEnabled: false, barkServerKey: '', emailEnabled: true }));
router.get('/audit-logs', (req, res) => res.json({ logs: [{ id: 1, action: 'demo.view', description: '打开演示控制台', created_at: new Date().toISOString(), username: 'Demo User' }], total: 1, page: 1, limit: 50 }));
module.exports = router;
