'use strict';
const fs = require('fs'); const os = require('os'); const path = require('path'); const test = require('node:test'); const assert = require('node:assert/strict'); const api = require('../src');
function env(name, value) { const old = process.env[name]; if (value === undefined) delete process.env[name]; else process.env[name] = value; return () => { if (old === undefined) delete process.env[name]; else process.env[name] = old; }; }
test('maps and safely normalizes Hook events', () => { assert.equal(api.mapHookEvent({ hookEventName: 'PostToolUse' }), 'tool_use'); assert.equal(api.mapHookEvent({ hook_event_name: 'session_start' }), 'session_start'); const p = api.normalizeHook({ sessionId: 's', toolName: 'Bash', toolInput: { command: 'secret' }, hookEventName: 'PreToolUse' }); assert.equal(p.event, 'tool_use'); assert.deepEqual(p.detail.tool_input_keys, ['command']); assert.equal(p.detail.tool_input, undefined); });
test('redacts credentials, URLs and JWTs', () => { const safe = api.clean('Authorization: Bearer abc token=xyz https://x.test/?token=secret eyJabcdefghijk.foo.bar'); assert.doesNotMatch(safe, /abc|xyz|secret|eyJabcdefghijk/); });
test('profiles are isolated and URL validated', () => { const restore = env('CR_REPORT_CONFIG', path.join(os.tmpdir(), `cr-profile-${process.pid}.json`)); try { fs.rmSync(api.configPath(), { force: true }); api.saveConfig({ profiles: { default: { url: 'http://a', key: 'a-secret' }, other: { url: 'http://b', key: 'b-secret' } }, current_profile: 'default', url:'http://a', key:'a-secret' }); api.use('other'); assert.equal(api.loadConfig().key, 'b-secret'); assert.throws(() => api.remove('other', true)); api.remove('default', true); assert.ok(api.loadConfig().profiles.other); assert.throws(() => api.validUrl('file:///tmp/x')); } finally { fs.rmSync(api.configPath(), { force: true }); restore(); } });
test('profile OAuth refresh uses named profile and isolated URL', async () => { const restore = env('CR_REPORT_CONFIG', path.join(os.tmpdir(), `cr-profile-oauth-${process.pid}.json`)); const seen=[]; const server=require('http').createServer((req,res)=>{ if(req.url==='/oauth/token'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{assert.match(body,/refresh_token=old-other/);res.setHeader('content-type','application/json');res.end(JSON.stringify({access_token:'new-other',refresh_token:'newer',expires_in:3600}))})}else{seen.push({auth:req.headers.authorization,url:req.url});res.setHeader('content-type','application/json');res.end('{}')}}); await new Promise(r=>server.listen(0,r)); try { const port=server.address().port; api.saveConfig({profiles:{default:{url:'http://127.0.0.1:1',key:'default-key'},other:{url:`http://127.0.0.1:${port}`,access_token:'old-other',refresh_token:'old-other',expires_at:1}},current_profile:'default',url:'http://127.0.0.1:1',key:'default-key'}); const token=await api.getAccessToken('other'); assert.equal(token,'new-other'); const r=await api.requestJson(`http://127.0.0.1:${port}/api/client-events/live`,{headers:{authorization:`Bearer ${token}`}},1000); assert.equal(r.statusCode,200); assert.equal(seen[0].auth,'Bearer new-other'); } finally { server.close();fs.rmSync(api.configPath(),{force:true});restore()} });
test('hook backup restore enforces exact schema and rejects appended hooks', () => { const gh=env('GROK_HOME',path.join(os.tmpdir(),`cr-hooks-${process.pid}`)); try { fs.rmSync(process.env.GROK_HOME,{recursive:true,force:true}); const cli=path.resolve(__dirname,'../bin/cr-report.js'); api.install(cli); const b=api.backup(); const data=JSON.parse(fs.readFileSync(b)); data.hooks.SessionStart[0].hooks.push({type:'command',command:'evil',timeout:5});fs.writeFileSync(b,JSON.stringify(data));assert.throws(()=>api.restore(b));data.hooks.SessionStart[0].hooks.pop();data.hooks.SessionStart.push(data.hooks.SessionStart[0]);fs.writeFileSync(b,JSON.stringify(data));assert.throws(()=>api.restore(b)); } finally { fs.rmSync(process.env.GROK_HOME,{recursive:true,force:true});gh(); } });
test('logs are private and follow directory observes creation and rotation', async () => { const restore=env('CR_REPORT_LOG',path.join(os.tmpdir(),`cr-follow-${process.pid}`,'events.log')); try { fs.rmSync(path.dirname(api.logPath()),{recursive:true,force:true}); const events=[]; const stop=api.followLogs((row)=>events.push(row)); api.writeLog({event:'tool_use',ok:true}); await new Promise(r=>setTimeout(r,30)); const rotated=`${api.logPath()}.old`;fs.renameSync(api.logPath(),rotated);fs.chmodSync(rotated,0o600);api.writeLog({event:'tool_use_failure',ok:false});await new Promise(r=>setTimeout(r,30));stop(); assert.ok(events.length>=2); assert.equal(fs.statSync(rotated).mode&0o077,0); } finally { fs.rmSync(path.dirname(api.logPath()),{recursive:true,force:true});restore(); } });
test('shell quoting supports Windows command generation and platform cache', () => { const old=process.platform; assert.equal(api.commandPath(api.shellQuote('/tmp/my cli/cr-report')+' hook --harness grok'),'/tmp/my cli/cr-report'); assert.match(api.watchState().statePath,/cr-report/); assert.equal(typeof old,'string'); });
test('TUI non-TTY lifecycle is testable', async () => { await api.runTui('/missing',{nonTtyMessage:false}); });
