const fs=require('fs'); const out='/tmp/desktop-blora21-browser'; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
class CDP{constructor(url){this.id=0;this.pending=new Map();this.events=[];this.ws=new WebSocket(url);this.ready=new Promise(r=>this.ws.onopen=r);this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);this.pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else this.events.push(m);};}async send(method,params={}){await this.ready;return new Promise((resolve,reject)=>{const id=++this.id;this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}));});}async eval(expression){const r=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;}}
(async()=>{const target=await(await fetch('http://127.0.0.1:18583/json/new?about:blank',{method:'PUT'})).json();const c=new CDP(target.webSocketDebuggerUrl);await c.send('Page.enable');await c.send('Runtime.enable');const results=[];let boot;
const snap=async name=>{await sleep(150);const r=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(`${out}/${name}.png`,Buffer.from(r.data,'base64'));};
const nav=async file=>{c.events=[];await c.send('Page.navigate',{url:`file:///data/CrewRouter/CrewRouter-Desktop/src/renderer/${file}.html`});await sleep(1800);for(let i=0;i<30;i++){if(await c.eval(`document.readyState==='complete' && typeof window.Blora==='object' && (document.getElementById('connection')?.children.length>0 || document.getElementById('saved-panel')?.hidden===false || !window.crewrouterDesktop)`))break;await sleep(100);}};
await nav('index');results.push({noBridge:await c.eval(`({view:document.getElementById('view-error').hidden,description:document.getElementById('error-result').getAttribute('description'),version:window.Blora?.VERSION})`)});await snap('no-bridge');
for(const width of [1280,390])for(const theme of ['light','dark']){
 await c.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});
 if(boot)await c.send('Page.removeScriptToEvaluateOnNewDocument',{identifier:boot});
 const source=`window.testCalls=[];let profiles=[{id:'p1',name:'测试服务器',url:'https://example.com',mode:'remote',edition:'team'}];let settings={autoConnect:false,notifications:true,updateChecks:true,theme:'${theme}',language:'zh'};let status={mode:'welcome',theme:'${theme}',language:'zh',runtime:'desktop-local',localServer:{ready:true,pid:123,port:3000},localProfile:{displayName:'测试用户'}};window.testStatus=fn=>{status=Object.assign(status,fn);window.statusListener?.(status);};window.crewrouterDesktop={getStatus:async()=>status,listProfiles:async()=>profiles,getDesktopSettings:async()=>({settings,profiles,status,local:status.localServer}),saveDesktopSettings:async s=>{testCalls.push(['save',s]);settings={...settings,...s};return settings},getDiagnostics:async()=>({version:'test-stub'}),onStatus:fn=>window.statusListener=fn,renameProfile:async(id,name)=>{testCalls.push(['rename',id,name]);profiles=profiles.map(p=>p.id===id?{...p,name}:p);return profiles;},deleteProfile:async id=>{testCalls.push(['delete',id]);profiles=profiles.filter(p=>p.id!==id);return profiles;},stopLocal:async()=>testCalls.push(['stop']),restartLocal:async()=>testCalls.push(['restart']),startLocal:async name=>testCalls.push(['startLocal',name]),connectCustomRemote:async url=>testCalls.push(['connect',url]),openOfficialLogin:async()=>testCalls.push(['official']),switchProfile:async id=>testCalls.push(['switch',id]),cancelPending:async()=>testCalls.push(['cancel']),reopenOfficialLogin:async()=>{},retry:async()=>{},clearError:async()=>{},openLogs:async()=>{},restartApp:async()=>{},quit:async()=>{}};`;
 boot=(await c.send('Page.addScriptToEvaluateOnNewDocument',{source})).identifier;
 const row={width,theme};await nav('index');await snap(`launcher-${theme}-${width}`);
 row.initial=await c.eval(`({version:window.Blora?.VERSION,field:!!customElements.get('blora-field'),overflow:document.documentElement.scrollWidth>innerWidth,scheme:document.documentElement.dataset.bloraColorScheme,errors:[]})`);
 await c.eval(`document.getElementById('profile-list').querySelector('blora-dropdown').dispatchEvent(new CustomEvent('blora-select',{detail:{value:'rename'},bubbles:true}));`);await snap(`rename-${theme}-${width}`);
 row.renameOpened=await c.eval(`document.getElementById('rename-dialog').hasAttribute('open')`);
 await c.eval(`document.getElementById('rename-field').querySelector('input').value='已重命名';document.getElementById('rename-field').querySelector('input').dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('rename-ok').click()`);await sleep(100);
 await c.eval(`document.getElementById('open-settings').click()`);await sleep(100);await snap(`launcher-settings-${theme}-${width}`);
 await c.eval(`document.getElementById('local-stop').click()`);await snap(`confirm-${theme}-${width}`);row.confirm=await c.eval(`document.getElementById('confirm-dialog').hasAttribute('open')`);await c.eval(`document.getElementById('confirm-ok').click()`);
 row.calls=await c.eval(`testCalls`);row.exceptions=c.events.filter(e=>e.method==='Runtime.exceptionThrown');
 await nav('settings');await snap(`settings-${theme}-${width}`);row.settings=await c.eval(`({overflow:document.documentElement.scrollWidth>innerWidth,scheme:document.documentElement.dataset.bloraColorScheme,disabled:document.getElementById('theme').hasAttribute('disabled')})`);
 await c.eval(`document.querySelector('[data-rename]').click()`);await snap(`settings-rename-${theme}-${width}`);row.settingsRename=await c.eval(`document.getElementById('settings-dialog').hasAttribute('open')`);
 await c.eval(`document.getElementById('dialog-name').value='旧页重命名';document.getElementById('dialog-ok').click()`);await sleep(100);
 await c.eval(`document.getElementById('stop').click()`);await sleep(50);await c.eval(`document.getElementById('dialog-ok').click()`);await sleep(100);
 row.settingsCalls=await c.eval(`testCalls`);row.settingsExceptions=c.events.filter(e=>e.method==='Runtime.exceptionThrown');results.push(row);
}
fs.writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));c.ws.close();})().catch(e=>{console.error(e);process.exit(1)});
