'use strict';
const fs = require('fs'); const path = require('path'); const { hookPath, scanHooks, EVENTS, commandPath } = require('./hooks');
function dir() { return path.join(path.dirname(hookPath()), 'backups'); }
function backup() { if (!fs.existsSync(hookPath())) throw new Error('Helper Hook 不存在'); fs.mkdirSync(dir(), { recursive: true }); const target = path.join(dir(), `crewrouter-helper.${Date.now()}.json`); fs.copyFileSync(hookPath(), target); fs.chmodSync(target, 0o600); return target; }
function listBackups() { try { return fs.readdirSync(dir()).filter((n) => /^crewrouter-helper\.\d+\.json$/.test(n)).sort().reverse().map((n) => ({ name: n, path: path.join(dir(), n) })); } catch { return []; } }
function controlled(file) { if (!file) { const candidates = listBackups(); if (!candidates.length) throw new Error('备份不存在'); file = candidates[0].path; } fs.mkdirSync(dir(), { recursive: true }); const base = fs.realpathSync(dir()); const target = path.resolve(file); if (!/^crewrouter-helper\.\d+\.json$/.test(path.basename(target)) || path.dirname(target) !== base) throw new Error('只允许恢复受控备份文件'); if (!fs.existsSync(target) || fs.realpathSync(target) !== target) throw new Error('拒绝符号链接备份'); return target; }
function ownKeys(value, keys) { return value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).sort().join('\0') === keys.slice().sort().join('\0'); }
function validateHookConfig(data) { if (!ownKeys(data, ['hooks']) || !ownKeys(data.hooks, EVENTS)) throw new Error('备份根对象或事件键无效'); const commands = []; for (const event of EVENTS) { const list = data.hooks[event]; if (!Array.isArray(list) || list.length !== 1) throw new Error(`${event} 事件数组长度无效`); const wrapper = list[0]; if (!ownKeys(wrapper, ['hooks']) || !Array.isArray(wrapper.hooks) || wrapper.hooks.length !== 1) throw new Error(`${event} hooks 数组无效`); const hook = wrapper.hooks[0]; if (!ownKeys(hook, ['type', 'command', 'timeout']) || hook.type !== 'command' || typeof hook.command !== 'string' || hook.timeout !== 5) throw new Error(`${event} Hook 元素无效`); commands.push(hook.command); } if (new Set(commands).size !== 1 || !commands[0].includes('hook --harness grok')) throw new Error('备份命令不一致或不是 Helper CLI'); const executable = commandPath(commands[0]); if (!executable) throw new Error('备份命令路径无效'); try { if (!fs.statSync(executable).isFile() || (process.platform !== 'win32' && !(fs.statSync(executable).mode & 0o111))) throw new Error('备份命令不可执行'); } catch { throw new Error('备份命令不可执行'); } return true; }
function restore(file) { const target = controlled(file); let data; try { data = JSON.parse(fs.readFileSync(target, 'utf8')); } catch { throw new Error('备份 JSON 损坏'); } validateHookConfig(data); const tmp = `${hookPath()}.${process.pid}.restore.tmp`; try { fs.writeFileSync(tmp, `${JSON.stringify(data, null, 2)}\n`, { mode: 0o600 }); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, hookPath()); } finally { try { fs.unlinkSync(tmp); } catch {} } return hookPath(); }
module.exports = { backup, listBackups, restore, controlled, dir, validateHookConfig };
