'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const http = require('http');
const https = require('https');
const OAUTH_CLIENT_ID = 'crewrouter-helper';
const REFRESH_AHEAD_SEC = 60;
function configPath() { return process.env.CR_REPORT_CONFIG || path.join(os.homedir(), '.config', 'cr-report.json'); }
function loadConfig() { try { const cfg = JSON.parse(fs.readFileSync(configPath(), 'utf8')); return cfg && typeof cfg === 'object' && !Array.isArray(cfg) ? cfg : null; } catch { return null; } }
function saveConfig(cfg) { const target = configPath(); fs.mkdirSync(path.dirname(target), { recursive: true }); const tmp = `${target}.${process.pid}.${Date.now()}.tmp`; try { fs.writeFileSync(tmp, `${JSON.stringify(cfg, null, 2)}\n`, { mode: 0o600 }); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, target); } finally { try { fs.unlinkSync(tmp); } catch {} } }
function credentialStatus(cfg = loadConfig()) { if (!cfg || (!cfg.access_token && !cfg.refresh_token && !cfg.key)) return { level: 'MISSING', label: '缺失' }; if (cfg.key && !cfg.access_token && !cfg.refresh_token) return { level: 'OK', label: '已配置静态 Key' }; const exp = Number(cfg.expires_at); if (!Number.isFinite(exp)) return { level: 'ERROR', label: 'expires_at 无效' }; if (exp <= Date.now() / 1000) return cfg.refresh_token ? { level: 'WARN', label: 'access token 已过期，将刷新' } : { level: 'ERROR', label: 'access token 已过期' }; if (exp <= Date.now() / 1000 + 86400) return { level: 'WARN', label: '即将过期' }; return { level: 'OK', label: '已配置' }; }
function activeProfile(cfg = loadConfig()) { if (!cfg) return null; const profiles = cfg.profiles && typeof cfg.profiles === 'object' ? cfg.profiles : {}; const name = cfg.current_profile || 'default'; return { name, profile: profiles[name] || cfg }; }
function getCredential(profile) { const cfg = loadConfig(); const selected = profile ? (cfg?.profiles?.[profile] || null) : activeProfile(cfg)?.profile; return { url: selected ? String(selected.url || '').replace(/\/$/, '') : null, token: selected ? (selected.access_token || selected.key || null) : null }; }
function requestJson(url, options, timeout = 5000) { return new Promise((resolve, reject) => { let req; try { const target = new URL(url); if (!['http:', 'https:'].includes(target.protocol)) throw new Error('protocol'); const transport = target.protocol === 'https:' ? https : http; req = transport.request(target, { ...options, timeout }, (res) => { let text = ''; res.setEncoding('utf8'); res.on('data', (chunk) => { text += chunk; }); res.on('end', () => { try { resolve({ statusCode: res.statusCode, body: JSON.parse(text) }); } catch { reject(new Error('invalid JSON')); } }); }); req.on('timeout', () => req.destroy(new Error('timeout'))); req.on('error', reject); if (options.body) req.write(options.body); req.end(); } catch (err) { reject(err); } }); }
async function refreshCredential(cfg, profileName) { const url = String(cfg.url || '').replace(/\/$/, ''); const body = new URLSearchParams({ grant_type: 'refresh_token', refresh_token: String(cfg.refresh_token), client_id: String(cfg.client_id || OAUTH_CLIENT_ID) }).toString(); const response = await requestJson(`${url}/oauth/token`, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded', 'content-length': Buffer.byteLength(body) }, body }, 10000); const token = response.body; if (response.statusCode < 200 || response.statusCode >= 300 || !token.access_token || !token.refresh_token) throw new Error('refresh failed'); const next = { ...cfg, access_token: String(token.access_token), refresh_token: String(token.refresh_token), expires_at: Date.now() / 1000 + Number(token.expires_in || 86400), client_id: cfg.client_id || OAUTH_CLIENT_ID }; const root = loadConfig() || {}; if (profileName && root.profiles?.[profileName]) root.profiles[profileName] = { ...root.profiles[profileName], ...next }; saveConfig(profileName && root.profiles?.[profileName] ? { ...root, ...next, profiles: root.profiles } : next); return next.access_token; }
async function withLock(fn) { const lock = `${configPath()}.lock`; fs.mkdirSync(path.dirname(lock), { recursive: true }); let handle; for (let i = 0; i < 100; i++) { try { handle = fs.openSync(lock, 'wx', 0o600); break; } catch (err) { if (err.code !== 'EEXIST') throw err; await new Promise((resolve) => setTimeout(resolve, 25)); } } if (handle === undefined) throw new Error('credential lock timeout'); try { return await fn(); } finally { try { fs.closeSync(handle); } catch {} try { fs.unlinkSync(lock); } catch {} } }
async function getAccessToken(profileName) { const root = loadConfig(); const active = profileName ? { name: profileName, profile: root?.profiles?.[profileName] } : activeProfile(root); const cfg = active?.profile; if (!cfg) return null; if (cfg.key && !cfg.refresh_token) return String(cfg.key); const exp = Number(cfg.expires_at); if (cfg.access_token && Number.isFinite(exp) && exp > Date.now() / 1000 + REFRESH_AHEAD_SEC) return String(cfg.access_token); if (!cfg.refresh_token) return null; return withLock(async () => { const freshRoot = loadConfig(); const fresh = profileName ? freshRoot?.profiles?.[profileName] : activeProfile(freshRoot)?.profile; const freshExp = Number(fresh && fresh.expires_at); if (fresh?.access_token && Number.isFinite(freshExp) && freshExp > Date.now() / 1000 + REFRESH_AHEAD_SEC) return String(fresh.access_token); return refreshCredential(fresh || cfg, profileName || active?.name); }); }
module.exports = { OAUTH_CLIENT_ID, configPath, loadConfig, saveConfig, activeProfile, getCredential, getAccessToken, refreshCredential, credentialStatus, requestJson, withLock };
