'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const { scanHooks, watchState, grokHome, hookPath } = require('./hooks');
const { configPath, loadConfig, credentialStatus, requestJson } = require('./config');
const { readLogs } = require('./logs');
function item(name, level, detail, fix = '') { return { name, level, detail, fix }; }
async function scanDoctor(command) { const cfg = loadConfig(); const hook = scanHooks(command); const checks = []; checks.push(item('Node', process.versions.node ? 'OK' : 'ERROR', process.versions.node)); checks.push(item('npm', 'OK', '可执行性由 npm CLI 检查')); checks.push(item('配置文件', cfg ? 'OK' : 'MISSING', configPath(), cfg ? '' : '运行 auth login 或 auth use-key')); checks.push(item('Grok hooks 目录', fs.existsSync(path.join(grokHome(), 'hooks')) ? 'OK' : 'MISSING', path.join(grokHome(), 'hooks'))); checks.push(item('CrewRouter Hook', hook.level, `${hook.events.length} 个事件`, '运行 hooks install')); checks.push(item('Orca/Bark Hook', 'OK', '未修改原生 Hook')); const oldPython = fs.existsSync(path.join(grokHome(), 'hooks', 'cr-report.py')); checks.push(item('旧 Python Hook', oldPython ? 'WARN' : 'OK', oldPython ? '仍存在' : '未发现', oldPython ? '确认避免重复上报' : '')); const watch = watchState(); checks.push(item('旧 watch', watch.level, watch.detail)); const credential = credentialStatus(cfg); checks.push(item('凭证', credential.level, credential.label)); let service = item('服务端', 'MISSING', '未配置'); if (cfg && cfg.url) { try { const u = new URL(cfg.url); if (!['http:', 'https:'].includes(u.protocol)) throw new Error('protocol'); const r = await requestJson(`${cfg.url.replace(/\/$/, '')}/api/client-events/live?window=30`, { method: 'GET', headers: { authorization: `Bearer ${cfg.access_token || cfg.key || ''}` } }, 1500); service = item('服务端', r.statusCode >= 200 && r.statusCode < 300 ? 'OK' : 'WARN', `HTTP ${r.statusCode}`); } catch { service = item('服务端', 'WARN', '不可达或超时', '检查 URL 和服务端状态'); } } checks.push(service); const recent = readLogs(); checks.push(item('最近上报', recent.length ? (recent[recent.length - 1].ok ? 'OK' : 'WARN') : 'MISSING', recent.length ? '已有安全日志' : '暂无本地记录')); checks.push(item('平台路径', 'OK', `${process.platform} / ${path.delimiter}`)); const levels = checks.map((c) => c.level); const overall = levels.includes('ERROR') ? 'ERROR' : levels.includes('WARN') ? 'WARN' : levels.includes('MISSING') ? 'MISSING' : 'OK'; return { checkedAt: new Date().toISOString(), overall, checks }; }
function formatDoctor(result) { return [`CrewRouterHelper doctor: ${result.overall}`, ...result.checks.map((c) => `${c.level.padEnd(7)} ${c.name}: ${c.detail}${c.fix ? `（建议：${c.fix}）` : ''}`), `检查时间: ${result.checkedAt}`].join('\n'); }
module.exports = { scanDoctor, formatDoctor };
