'use strict';
const fs = require('fs'); const os = require('os'); const path = require('path'); const { execFileSync } = require('child_process');
const EVENTS = ['SessionStart','SessionEnd','PreToolUse','PostToolUse','PostToolUseFailure','PermissionDenied','Stop','StopFailure','Notification','SubagentStart','SubagentStop','PreCompact','PostCompact'];
function grokHome() { return process.env.GROK_HOME || path.join(os.homedir(), '.grok'); } function hookPath() { return path.join(grokHome(), 'hooks', 'crewrouter-helper.json'); }
function shellQuote(value) { return `'${String(value).replace(/'/g, `'\\''`)}'`; }
function hookConfig(command) { return { hooks: Object.fromEntries(EVENTS.map((event) => [event, [{ hooks: [{ type: 'command', command, timeout: 5 }] }]])) }; }
function install(command) { if (!path.isAbsolute(command)) throw new Error('Hook CLI 路径必须是绝对路径'); const dir = path.dirname(hookPath()); fs.mkdirSync(dir, { recursive: true }); const tmp = path.join(dir, `.${path.basename(hookPath())}.${process.pid}.${Date.now()}.tmp`); try { fs.writeFileSync(tmp, `${JSON.stringify(hookConfig(`${shellQuote(command)} hook --harness grok`), null, 2)}\n`, { mode: 0o600 }); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, hookPath()); } finally { try { fs.unlinkSync(tmp); } catch {} } return hookPath(); }
function uninstall() { try { fs.unlinkSync(hookPath()); return true; } catch (err) { if (err.code === 'ENOENT') return false; throw err; } }
function commandPath(command) { const match = String(command || '').match(/^'((?:[^']|'\\'')+)'(?:\s|$)|^"((?:[^"\\]|\\.)+)"(?:\s|$)|^([^\s]+)(?:\s|$)/); if (!match) return null; return (match[1] || match[2] || match[3]).replace(/'\\''/g, "'").replace(/\\([\\"])/g, '$1'); }
function isExecutable(file) { try { return Boolean(file && fs.statSync(file).isFile() && (fs.statSync(file).mode & 0o111)); } catch { return false; } }
function scanHooks(expectedCommand) { const file = hookPath(); const result = { path: file, exists: false, valid: false, level: 'MISSING', events: [], command: null, commandExecutable: false, consistent: false }; try { result.exists = fs.existsSync(file); if (!result.exists) return result; if (!fs.statSync(file).isFile()) { result.level = 'ERROR'; return result; } const data = JSON.parse(fs.readFileSync(file, 'utf8')); const entries = data.hooks; if (!entries || typeof entries !== 'object' || Array.isArray(entries)) throw new Error('hooks structure'); result.events = Object.keys(entries); if (!result.events.length || result.events.some((event) => !EVENTS.includes(event))) throw new Error('unsupported event'); const commands = result.events.map((event) => entries[event]?.[0]?.hooks?.[0]); if (commands.some((entry) => !entry || entry.type !== 'command' || typeof entry.command !== 'string' || entry.timeout !== 5)) throw new Error('invalid hook entry'); result.command = commands[0].command; result.consistent = commands.every((entry) => entry.command === result.command); const filePath = commandPath(result.command); result.commandExecutable = isExecutable(filePath); result.valid = result.consistent && result.commandExecutable; result.level = result.valid ? 'OK' : 'WARN'; } catch { result.level = 'ERROR'; } return result; }
function watchState() { const statePath = path.join(os.homedir(), '.cache', 'cr-report-grok-state.json'); let processes = []; try { const ps = execFileSync('ps', ['-eo', 'pid=,args='], { encoding: 'utf8', timeout: 1000 }); processes = ps.split('\n').filter((line) => /cr-report(?:\.py|\.js)?\s+watch\b/.test(line) && !line.includes('grep')); } catch {} const running = processes.length > 0; let stale = false; try { stale = Date.now() - fs.statSync(statePath).mtimeMs > 120000; } catch {} return { running, stale, statePath, present: fs.existsSync(statePath), level: running ? 'WARN' : (stale ? 'WARN' : 'OK'), detail: running ? '正在运行（兼容兜底；不要与原生 Hook 并用）' : '未运行' }; }
module.exports = { EVENTS, grokHome, hookPath, hookConfig, shellQuote, install, uninstall, commandPath, scanHooks, watchState };
