'use strict';
const fs = require('fs'); const os = require('os'); const path = require('path'); const { execFileSync } = require('child_process');
const EVENTS = ['SessionStart','SessionEnd','PreToolUse','PostToolUse','PostToolUseFailure','PermissionDenied','Stop','StopFailure','Notification','SubagentStart','SubagentStop','PreCompact','PostCompact'];
function cacheDir() { return process.env.XDG_CACHE_HOME || process.env.LOCALAPPDATA || path.join(os.homedir(), '.cache'); }
function grokHome() { return process.env.GROK_HOME || path.join(os.homedir(), '.grok'); } function hookPath() { return path.join(grokHome(), 'hooks', 'crewrouter-helper.json'); }
function shellQuote(value) { const text = String(value); if (process.platform === 'win32') return `"${text.replace(/(["\\])/g, '\\$1')}"`; return `'${text.replace(/'/g, `'\\''`)}'`; }
function hookConfig(command) { return { hooks: Object.fromEntries(EVENTS.map((event) => [event, [{ hooks: [{ type: 'command', command, timeout: 5 }] }]])) }; }
function installCommand(command) { if (!path.isAbsolute(command)) throw new Error('Hook CLI 路径必须是绝对路径'); return `${process.platform === 'win32' ? `${shellQuote(process.execPath)} ${shellQuote(command)}` : shellQuote(command)} hook --harness grok`; }
function commandParts(command) { const text = String(command || ''); let match = text.match(/^'((?:[^']|'\\'')+)'(?:\s+(.*))?$/); if (!match) match = text.match(/^"((?:[^"\\]|\\.)+)"(?:\s+(.*))?$/); if (!match) match = text.match(/^([^\s]+)(?:\s+(.*))?$/); return match ? { path: (match[1] || '').replace(/'\\''/g, "'").replace(/\\([\\"])/g, '$1'), args: match[2] || '' } : null; }
function isControlledCommand(command, expectedCommand) { const actual = commandParts(command); const expected = commandParts(expectedCommand); if (!actual || !expected || actual.args !== 'hook --harness grok' || expected.args !== 'hook --harness grok') return false; try { const actualStat = fs.lstatSync(actual.path); const expectedStat = fs.lstatSync(expected.path); if (!actualStat.isFile() || actualStat.isSymbolicLink() || !expectedStat.isFile() || expectedStat.isSymbolicLink()) return false; if (process.platform !== 'win32' && !(actualStat.mode & 0o111)) return false; return fs.realpathSync(actual.path) === fs.realpathSync(expected.path); } catch { return false; } }
function isHelperConfig(data, expectedCommand) { if (!data || typeof data !== 'object' || Array.isArray(data) || Object.keys(data).sort().join('\0') !== 'hooks') return false; if (!data.hooks || typeof data.hooks !== 'object' || Array.isArray(data.hooks) || Object.keys(data.hooks).sort().join('\0') !== EVENTS.slice().sort().join('\0')) return false; let command = null; for (const event of EVENTS) { const list = data.hooks[event]; if (!Array.isArray(list) || list.length !== 1 || !list[0] || Object.keys(list[0]).sort().join('\0') !== 'hooks' || !Array.isArray(list[0].hooks) || list[0].hooks.length !== 1) return false; const hook = list[0].hooks[0]; if (!hook || Object.keys(hook).sort().join('\0') !== 'command\0timeout\0type' || hook.type !== 'command' || typeof hook.command !== 'string' || hook.timeout !== 5) return false; if (command === null) command = hook.command; else if (hook.command !== command) return false; } return Boolean(command && expectedCommand && isControlledCommand(command, expectedCommand)); }
function installPlan(command) { const target = hookPath(); const expectedCommand = installCommand(command); const exists = fs.existsSync(target); let helper = false; if (exists) { try { helper = isHelperConfig(JSON.parse(fs.readFileSync(target, 'utf8')), expectedCommand); } catch {} } return { path: target, exists, helper, conflict: exists && !helper, command: expectedCommand, will_write: !exists || helper, will_backup: exists && helper }; }
function install(command) { const plan = installPlan(command); if (plan.conflict) throw new Error('目标 Hook 已存在且不是 Helper 配置，拒绝覆盖'); const dir = path.dirname(plan.path); fs.mkdirSync(dir, { recursive: true }); if (plan.exists) { const backupDir = path.join(dir, 'backups'); fs.mkdirSync(backupDir, { recursive: true }); const backupFile = path.join(backupDir, `crewrouter-helper.${Date.now()}.json`); fs.copyFileSync(plan.path, backupFile); fs.chmodSync(backupFile, 0o600); } const tmp = path.join(dir, `.${path.basename(plan.path)}.${process.pid}.${Date.now()}.tmp`); try { fs.writeFileSync(tmp, `${JSON.stringify(hookConfig(plan.command), null, 2)}\n`, { mode: 0o600 }); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, plan.path); } finally { try { fs.unlinkSync(tmp); } catch {} } return plan.path; }
function uninstall() { try { fs.unlinkSync(hookPath()); return true; } catch (err) { if (err.code === 'ENOENT') return false; throw err; } }
function commandPath(command) { const match = String(command || '').match(/^'((?:[^']|'\\'')+)'(?:\s|$)|^"((?:[^"\\]|\\.)+)"(?:\s|$)|^([^\s]+)(?:\s|$)/); if (!match) return null; return (match[1] || match[2] || match[3]).replace(/'\\''/g, "'").replace(/\\([\\"])/g, '$1'); }
function isExecutable(file) { try { return Boolean(file && fs.statSync(file).isFile() && (process.platform === 'win32' || fs.statSync(file).mode & 0o111)); } catch { return false; } }
function scanHooks(expectedCommand) { const file = hookPath(); const result = { path: file, exists: false, valid: false, level: 'MISSING', events: [], command: null, commandExecutable: false, consistent: false }; try { result.exists = fs.existsSync(file); if (!result.exists) return result; if (!fs.statSync(file).isFile()) { result.level = 'ERROR'; return result; } const data = JSON.parse(fs.readFileSync(file, 'utf8')); const entries = data.hooks; if (!entries || typeof entries !== 'object' || Array.isArray(entries)) throw new Error('hooks structure'); result.events = Object.keys(entries); if (!result.events.length || result.events.some((event) => !EVENTS.includes(event))) throw new Error('unsupported event'); const commands = result.events.map((event) => entries[event]?.[0]?.hooks?.[0]); if (commands.some((entry) => !entry || entry.type !== 'command' || typeof entry.command !== 'string' || entry.timeout !== 5)) throw new Error('invalid hook entry'); result.command = commands[0].command; result.consistent = commands.every((entry) => entry.command === result.command); const filePath = commandPath(result.command); result.commandExecutable = isExecutable(filePath); result.valid = result.consistent && result.commandExecutable; result.level = result.valid ? 'OK' : 'WARN'; } catch { result.level = 'ERROR'; } return result; }
function watchState() { const statePath = path.join(cacheDir(), 'cr-report', 'cr-report-grok-state.json'); let processes = []; try { const ps = process.platform === 'win32' ? execFileSync('tasklist', ['/FO', 'CSV', '/NH'], { encoding: 'utf8', timeout: 1000 }) : execFileSync('ps', ['-eo', 'pid=,args='], { encoding: 'utf8', timeout: 1000 }); processes = ps.split('\n').filter((line) => /cr-report(?:\.py|\.js)?\s+watch\b/.test(line) && !line.includes('grep')); } catch {} const running = processes.length > 0; let stale = false; try { stale = Date.now() - fs.statSync(statePath).mtimeMs > 120000; } catch {} return { running, stale, statePath, present: fs.existsSync(statePath), level: running ? 'WARN' : (stale ? 'WARN' : 'OK'), detail: running ? '正在运行（兼容兜底；不要与原生 Hook 并用）' : '未运行' }; }
module.exports = { EVENTS, cacheDir, grokHome, hookPath, hookConfig, shellQuote, installCommand, installPlan, install, uninstall, commandPath, scanHooks, watchState };
