'use strict';
const fs = require('fs'); const os = require('os'); const path = require('path');
function logPath() { return process.env.CR_REPORT_LOG || path.join(process.env.XDG_CACHE_HOME || process.env.LOCALAPPDATA || path.join(os.homedir(), '.cache'), 'cr-report', 'events.log'); }
function clean(value) { return String(value == null ? '' : value).replace(/authorization\s*[:=]\s*(?:bearer\s+)?[^\s,;]+(?:\s+[^\s,;]+)?/gi, 'Authorization: [REDACTED]').replace(/bearer\s+[^\s,;]+/gi, 'Bearer [REDACTED]').replace(/((?:api[_-]?key|access[_-]?token|refresh[_-]?token|key|token|secret|password)\s*[:=]\s*)[^\s,;]+/gi, '$1[REDACTED]').replace(/https?:\/\/[^\s]+/gi, (url) => { try { const u = new URL(url); u.username=''; u.password=''; u.search=''; u.hash=''; return u.toString().replace(/\/$/,''); } catch { return '[REDACTED_URL]'; } }).replace(/\beyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\b/g, '[REDACTED_JWT]').slice(0, 256); }
function writeLog(entry) { const allowed = { ts: new Date().toISOString(), profile: clean(entry.profile || 'default').replace(/[^A-Za-z0-9_.-]/g, '_').slice(0, 64), event: ['session_start','session_end','prompt_submit','tool_use','tool_use_failure','permission_denied','response_stop','response_stop_failure','notification','subagent_start','subagent_stop','pre_compact','post_compact'].includes(entry.event) ? entry.event : 'other', ok: Boolean(entry.ok), status: Number.isFinite(entry.status) ? entry.status : null, latency_ms: Number.isFinite(entry.latency_ms) ? entry.latency_ms : null, error: clean(entry.error || '') }; const target = logPath(); const line = JSON.stringify(allowed) + '\n'; if (line.length > 2048) return; try { fs.mkdirSync(path.dirname(target), { recursive: true }); if (fs.existsSync(target) && fs.statSync(target).size > 1024 * 1024) { const rotated = `${target}.${Date.now()}`; fs.renameSync(target, rotated); fs.chmodSync(rotated, 0o600); } fs.appendFileSync(target, line, { mode: 0o600 }); fs.chmodSync(target, 0o600); } catch {} }
function readLogs() { try { return fs.readFileSync(logPath(), 'utf8').split('\n').filter(Boolean).slice(-500).map((line) => { try { return JSON.parse(line); } catch { return { error: 'invalid log entry' }; } }); } catch { return []; } }
function clearLogs() { try { fs.unlinkSync(logPath()); return true; } catch (err) { if (err.code === 'ENOENT') return false; throw err; } }
function followLogs(onLine = () => {}) { const target = logPath(); const parent = path.dirname(target); fs.mkdirSync(parent, { recursive: true }); let closed = false; let watcher; const emit = () => { if (!closed) onLine(readLogs().slice(-1)[0] || null); }; try { watcher = fs.watch(parent, (event, name) => { if (String(name) === path.basename(target) && (event === 'rename' || event === 'change')) emit(); }); } catch (err) { throw new Error(`无法监听日志目录：${err.message}`); } return () => { if (closed) return; closed = true; watcher.close(); }; }
module.exports = { logPath, clean, writeLog, readLogs, clearLogs, followLogs };
