'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { configPath, loadConfig, saveConfig } = require('./config');
const { grokHome, hookPath, EVENTS, hookConfig, installCommand, commandPath } = require('./hooks');

function backupDir() { return process.env.CR_REPORT_BACKUP_DIR || path.join(path.dirname(configPath()), 'crewrouter-helper-backups'); }
function safeId(id) { if (!/^[A-Za-z0-9][A-Za-z0-9_.-]{7,127}$/.test(String(id))) throw new Error('备份 ID 无效'); return String(id); }
function fileDigest(file) { return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
function ownFile(file) { const resolved = path.resolve(file); const allowed = [path.resolve(configPath()), path.resolve(hookPath())]; return allowed.includes(resolved); }
function listMigrationBackups() { try { return fs.readdirSync(backupDir(), { withFileTypes: true }).filter(x => x.isDirectory() && /^[A-Za-z0-9][A-Za-z0-9_.-]{7,127}$/.test(x.name)).map(x => { const files = []; for (const name of ['config.json', 'hook.json']) { const file = path.join(backupDir(), x.name, name); if (fs.existsSync(file)) files.push(name); } return { id: x.name, files, path: path.join(backupDir(), x.name) }; }).sort((a,b) => b.id.localeCompare(a.id)); } catch { return []; } }
function createBackup() { const id = `${Date.now()}-${crypto.randomBytes(5).toString('hex')}`; const dir = path.join(backupDir(), id); fs.mkdirSync(dir, { recursive: true, mode: 0o700 }); const manifest = { id, created_at: new Date().toISOString(), files: [] }; for (const [source, name] of [[configPath(), 'config.json'], [hookPath(), 'hook.json']]) { try { if (fs.statSync(source).isFile() && !fs.lstatSync(source).isSymbolicLink()) { fs.copyFileSync(source, path.join(dir, name)); fs.chmodSync(path.join(dir, name), 0o600); manifest.files.push({ name, sha256: fileDigest(source) }); } } catch {} } fs.writeFileSync(path.join(dir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, { mode: 0o600 }); return { id, path: dir, files: manifest.files.map(x => x.name) }; }
function listBackups() { const { listBackups: listHookBackups } = require('./backup'); return listHookBackups(); }
function backupPath(id) { const dir = path.join(backupDir(), safeId(id)); const root = path.resolve(backupDir()); if (path.dirname(dir) !== root || !fs.existsSync(path.join(dir, 'manifest.json'))) throw new Error('备份不存在'); return dir; }
function atomicCopy(source, target) { const tmp = `${target}.${process.pid}.${Date.now()}.tmp`; try { fs.copyFileSync(source, tmp); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, target); } finally { try { fs.unlinkSync(tmp); } catch {} } }
function restoreBackup(id) { const dir = backupPath(id); const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8')); for (const entry of manifest.files || []) { const source = path.join(dir, entry.name); const target = entry.name === 'config.json' ? configPath() : hookPath(); if (!ownFile(target) || !fs.statSync(source).isFile()) throw new Error('备份文件不受控'); fs.mkdirSync(path.dirname(target), { recursive: true }); atomicCopy(source, target); } return { id, restored: manifest.files.map(x => x.name) }; }
function planMigration() { const cfg = loadConfig(); const actions = []; let next = cfg ? { ...cfg } : null; if (cfg && !cfg.profiles && cfg.url) { const profile = {}; for (const k of ['url','key','access_token','refresh_token','expires_at','client_id','scope']) if (cfg[k] !== undefined) profile[k] = cfg[k]; next = { profiles: { default: profile }, current_profile: 'default', ...profile }; actions.push('将旧 Python 单配置转换为 default profile'); } if (cfg && cfg.profiles && !cfg.current_profile) { next.current_profile = 'default' in cfg.profiles ? 'default' : Object.keys(cfg.profiles)[0]; actions.push('补充 current_profile'); } const target = hookPath(); try { const data = JSON.parse(fs.readFileSync(target, 'utf8')); const command = data.hooks?.SessionStart?.[0]?.hooks?.[0]?.command; if (typeof command === 'string' && /cr-report\.py(?:\s|$)/.test(command)) { const cli = path.resolve(__dirname, '../bin/cr-report.js'); next = next || cfg; actions.push('将 Helper 旧 Python Hook 路径迁移到当前 CLI'); } } catch {} return { dry_run: true, actions, config: next, hook: actions.some(x => x.includes('Hook')) }; }
function migrate(yes = false) { const plan = planMigration(); if (!yes) return plan; if (!plan.actions.length) return { dry_run: false, changed: false, actions: [] }; const backup = createBackup(); try { if (plan.config) saveConfig(plan.config); const target = hookPath(); let data; try { data = JSON.parse(fs.readFileSync(target, 'utf8')); } catch { data = null; } if (data) { const old = data.hooks?.SessionStart?.[0]?.hooks?.[0]?.command; if (typeof old === 'string' && /cr-report\.py(?:\s|$)/.test(old)) { const command = installCommand(path.resolve(__dirname, '../bin/cr-report.js')); const replacement = hookConfig(command); for (const event of EVENTS) if (data.hooks?.[event]) data.hooks[event] = replacement.hooks[event]; atomicWriteJson(target, data); } } return { dry_run: false, changed: true, backup_id: backup.id, actions: plan.actions }; } catch (err) { try { restoreBackup(backup.id); } catch {} throw new Error(`迁移失败，已回滚：${err.message}`); } }
function atomicWriteJson(target, data) { const tmp = `${target}.${process.pid}.${Date.now()}.tmp`; try { fs.writeFileSync(tmp, `${JSON.stringify(data, null, 2)}\n`, { mode: 0o600 }); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, target); } finally { try { fs.unlinkSync(tmp); } catch {} } }
function rollback(id) { const selected = id || listBackups()[0]?.id; if (!selected) throw new Error('没有可回滚备份'); return restoreBackup(selected); }
module.exports = { backupDir, listBackups, listMigrationBackups, createBackup, restoreBackup, planMigration, migrate, rollback, safeId };
