'use strict';
const dns = require('dns').promises;
const net = require('net');
const tls = require('tls');
const fs = require('fs');
const { requestJson, getAccessToken, credentialStatus, activeProfile, loadConfig } = require('./config');
const { scanHooks } = require('./hooks');
function targetInfo(value) { try { const u = new URL(String(value)); if (!['http:','https:'].includes(u.protocol)) return { level:'ERROR', detail:'仅支持 http/https' }; return { url:u, level:'OK', detail:`${u.protocol}//${u.hostname}${u.port ? `:${u.port}` : ''}` }; } catch { return { level:'ERROR', detail:'URL 格式无效' }; } }
function tcp(host, port, timeout=1000) { return new Promise(resolve => { const s=net.connect({host,port,timeout},()=>{s.destroy();resolve({level:'OK',detail:'TCP 可达'});}); s.once('timeout',()=>{s.destroy();resolve({level:'WARN',detail:'TCP 超时'});}); s.once('error',()=>resolve({level:'WARN',detail:'TCP 不可达'})); }); }
function tlsProbe(host, port, timeout=1200) { return new Promise(resolve => { const s=tls.connect({host,port,servername:host,rejectUnauthorized:true,timeout},()=>{s.end();resolve({level:'OK',detail:'TLS 建连成功'});}); s.once('timeout',()=>{s.destroy();resolve({level:'WARN',detail:'TLS 超时'});}); s.once('error',()=>{s.destroy();resolve({level:'WARN',detail:'TLS 建连失败'});}); }); }
async function diagnose(cfg, options = {}) { const out=[]; const t=targetInfo(cfg?.url); out.push({name:'URL',...t}); if(t.level!=='OK' || options.localOnly) return out; const host=t.url.hostname, port=Number(t.url.port)||(t.url.protocol==='https:'?443:80); try { await dns.lookup(host); out.push({name:'DNS',level:'OK',detail:'解析成功'}); } catch { out.push({name:'DNS',level:'WARN',detail:'解析失败'}); return out; } const tcpResult=await tcp(host,port); out.push({name:'TCP',...tcpResult}); if(t.url.protocol==='https:') out.push({name:'TLS',...(await tlsProbe(host,port))}); try { const r=await requestJson(`${t.url.origin}/api/client-events/live?window=30`,{method:'GET',headers:{accept:'application/json'}},1500); out.push({name:'HTTP',level:r.statusCode>=200&&r.statusCode<300?'OK':(r.statusCode===401||r.statusCode===403?'WARN':'ERROR'),detail:`HTTP ${r.statusCode}`}); } catch { out.push({name:'HTTP',level:'WARN',detail:'HTTP 建连超时或响应无效'}); } try { const token=await getAccessToken(); out.push({name:'凭证',...credentialStatus(activeProfile(cfg)?.profile||cfg),detail:token?'凭证可用':'凭证不可用'}); if(token) { const r=await requestJson(`${t.url.origin}/api/client-events/live?window=30`,{headers:{authorization:`Bearer ${token}`,accept:'application/json'}},1500); out.push({name:'事件权限',level:r.statusCode===200?'OK':(r.statusCode===401||r.statusCode===403?'WARN':'ERROR'),detail:`HTTP ${r.statusCode}`}); } } catch { out.push({name:'凭证',level:'WARN',detail:'凭证检查失败'}); } return out; }
async function heartbeat(command) { const cfg = loadConfig(); const hook = scanHooks(command); const local = [{ name:'CLI', level:fs.existsSync(command) ? 'OK' : 'ERROR', detail:'CLI 可执行文件' }, { name:'Hook', level:hook.valid?'OK':hook.level==='ERROR'?'ERROR':'WARN', detail:hook.valid?'Helper Hook 已就绪':'Helper Hook 未就绪' }, { name:'配置', level:cfg?'OK':'WARN', detail:cfg?'配置文件已存在':'配置文件缺失' }]; const remote = await diagnose(cfg); const mapped = remote.map(x => ({ name: x.name === 'HTTP' ? 'Router 健康' : x.name === '事件权限' ? 'client-events 权限' : x.name === '凭证' ? '认证' : x.name, level:x.level, detail:x.detail })); const names = new Set(mapped.map(x => x.name)); if (!names.has('认证')) mapped.push({name:'认证',level:'WARN',detail:'凭证不可用'}); if (!names.has('client-events 权限')) mapped.push({name:'client-events 权限',level:'WARN',detail:'未执行远程权限检查'}); if (!names.has('Router 健康')) mapped.push({name:'Router 健康',level:'WARN',detail:'未执行远程健康检查'}); const all = local.concat(mapped); const levels=all.map(x=>x.level); return { checkedAt:new Date().toISOString(), overall:levels.includes('ERROR')?'ERROR':levels.includes('WARN')?'WARN':'OK', checks:all }; }
module.exports={targetInfo,diagnose,heartbeat};
