'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { clean } = require('./logs');
function queuePath() { return process.env.CR_REPORT_QUEUE || path.join(process.env.XDG_CACHE_HOME || process.env.LOCALAPPDATA || path.join(os.homedir(), '.cache'), 'cr-report', 'queue.jsonl'); }
function safePayload(payload) { const out = { harness: String(payload.harness || '').slice(0, 32), event: String(payload.event || '').slice(0, 64), session_id: payload.session_id ? String(payload.session_id).slice(0, 128) : null, tool_name: payload.tool_name ? String(payload.tool_name).slice(0, 128) : null, cwd: payload.cwd ? clean(payload.cwd).slice(0, 256) : null, ts: Number(payload.ts) || Math.floor(Date.now() / 1000), detail: {} }; for (const key of ['source', 'reason', 'message', 'error']) if (typeof payload.detail?.[key] === 'string') out.detail[key] = clean(payload.detail[key]); if (Array.isArray(payload.detail?.tool_input_keys)) out.detail.tool_input_keys = payload.detail.tool_input_keys.slice(0, 32).map((x) => clean(x).slice(0, 64)); return out; }
function settings() { return { max: Math.max(10, Math.min(10000, Number(process.env.CR_REPORT_QUEUE_MAX) || 1000)), ttl: Math.max(3600, Number(process.env.CR_REPORT_QUEUE_TTL) || 7 * 86400), retries: Math.max(1, Math.min(20, Number(process.env.CR_REPORT_QUEUE_RETRIES) || 5)) }; }
function readQueue() { try { return fs.readFileSync(queuePath(), 'utf8').split('\n').filter(Boolean).map((line) => JSON.parse(line)).filter((x) => x && x.payload); } catch { return []; } }
function writeQueue(rows) { const file = queuePath(); fs.mkdirSync(path.dirname(file), { recursive: true }); const tmp = `${file}.${process.pid}.${Date.now()}.tmp`; try { fs.writeFileSync(tmp, rows.map((x) => JSON.stringify(x)).join('\n') + (rows.length ? '\n' : ''), { mode: 0o600 }); fs.chmodSync(tmp, 0o600); fs.renameSync(tmp, file); } finally { try { fs.unlinkSync(tmp); } catch {} } }
function enqueue(payload, reason = 'report failed') { try { const cfg = settings(); const safe = safePayload(payload); const key = crypto.createHash('sha256').update(JSON.stringify(safe)).digest('hex').slice(0, 24); const rows = readQueue(); if (rows.some((x) => x.key === key)) return false; rows.push({ key, payload: safe, created_at: Date.now(), attempts: 0, next_retry_at: Date.now(), last_error: clean(reason).slice(0, 160) }); writeQueue(rows.slice(-cfg.max)); return true; } catch { return false; } }
function summary() { const rows = readQueue(); const oldest = rows.reduce((a, x) => Math.min(a, x.created_at || Date.now()), Infinity); return { path: queuePath(), count: rows.length, oldest: Number.isFinite(oldest) ? new Date(oldest).toISOString() : null, last_error: rows[rows.length - 1]?.last_error || null }; }
function clearQueue() { try { fs.unlinkSync(queuePath()); return true; } catch (e) { if (e.code === 'ENOENT') return false; throw e; } }
function pruneQueue() { const now = Date.now(); const cfg = settings(); const rows = readQueue().filter((x) => now - Number(x.created_at || now) <= cfg.ttl && Number(x.attempts || 0) < cfg.retries); writeQueue(rows); return rows.length; }
async function retryQueue(send) { const now = Date.now(); const cfg = settings(); const rows = readQueue(); const keep = []; let sent = 0; for (const row of rows) { if (Number(row.next_retry_at || 0) > now) { keep.push(row); continue; } try { if (await send(row.payload)) { sent++; continue; } throw new Error('remote rejected'); } catch (e) { row.attempts = Number(row.attempts || 0) + 1; row.last_error = clean(e.message || 'retry failed').slice(0, 160); row.next_retry_at = Date.now() + Math.min(3600000, 1000 * 2 ** Math.min(row.attempts, 10)); if (row.attempts < cfg.retries) keep.push(row); } } writeQueue(keep); return { sent, remaining: keep.length }; }
module.exports = { queuePath, safePayload, readQueue, enqueue, summary, clearQueue, pruneQueue, retryQueue, settings };
