'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');const {clean}=require('./logs');
function queuePath(){return process.env.CR_REPORT_QUEUE||path.join(process.env.XDG_CACHE_HOME||process.env.LOCALAPPDATA||path.join(os.homedir(),'.cache'),'cr-report','queue.jsonl')}function deadPath(){return `${queuePath()}.dead.jsonl`}function lockPath(){return `${queuePath()}.lock`}
async function withLock(fn){fs.mkdirSync(path.dirname(queuePath()),{recursive:true});let h;const start=Date.now();while(Date.now()-start<5000){try{h=fs.openSync(lockPath(),'wx',0o600);break}catch(e){if(e.code!=='EEXIST')throw e;await new Promise(r=>setTimeout(r,25))}}if(h===undefined)throw Error('队列锁超时');try{return await fn()}finally{try{fs.closeSync(h)}catch{}try{fs.unlinkSync(lockPath())}catch{}}}
function detailed(file=queuePath()){const rows=[],errors=[];let text;try{text=fs.readFileSync(file,'utf8')}catch(e){if(e.code==='ENOENT')return{rows,errors};throw e}for(const [i,line] of text.split('\n').entries()){if(!line.trim())continue;try{const x=JSON.parse(line);if(x&&x.payload&&x.key)rows.push(x);else errors.push(`第 ${i+1} 行结构无效`)}catch{errors.push(`第 ${i+1} 行 JSON 损坏`)}}return{rows,errors}}
function settings(){return{max:Math.max(10,Math.min(10000,Number(process.env.CR_REPORT_QUEUE_MAX)||1000)),ttl:Math.max(3600,Number(process.env.CR_REPORT_QUEUE_TTL)||604800),retries:Math.max(1,Math.min(20,Number(process.env.CR_REPORT_QUEUE_RETRIES)||5))}}function safePayload(p){return{event_id:typeof p.event_id==='string'&&/^[A-Za-z0-9_-]{16,128}$/.test(p.event_id)?p.event_id:crypto.randomBytes(16).toString('hex'),harness:String(p.harness||'').slice(0,32),event:String(p.event||'').slice(0,64),session_id:p.session_id?String(p.session_id).slice(0,128):null,tool_name:p.tool_name?String(p.tool_name).slice(0,128):null,cwd:p.cwd?clean(p.cwd).slice(0,256):null,ts:Number(p.ts)||Math.floor(Date.now()/1000),detail:{}}}
function write(file,rows){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;try{fs.writeFileSync(tmp,rows.map(x=>JSON.stringify(x)).join('\n')+(rows.length?'\n':''),{mode:0o600});fs.chmodSync(tmp,0o600);fs.renameSync(tmp,file)}finally{try{fs.unlinkSync(tmp)}catch{}}}
async function enqueue(payload,reason='report failed'){try{return await withLock(()=>{const d=detailed();if(d.errors.length)throw Error('队列损坏');const x={key:crypto.randomBytes(12).toString('hex'),payload:safePayload(payload),created_at:Date.now(),attempts:0,next_retry_at:Date.now(),last_error:clean(reason).slice(0,160)};write(queuePath(),d.rows.concat(x).slice(-settings().max));return true})}catch{return false}}
function summary(){try{const d=detailed(),dead=detailed(deadPath());const oldest=d.rows.reduce((a,x)=>Math.min(a,x.created_at||Date.now()),Infinity);return{path:queuePath(),count:d.rows.length,dead_letter_count:dead.rows.length,oldest:Number.isFinite(oldest)?new Date(oldest).toISOString():null,last_error:d.rows.at(-1)?.last_error||null,corrupt:d.errors.length,error:d.errors.length?'queue contains invalid records':null}}catch(e){return{path:queuePath(),count:null,dead_letter_count:0,oldest:null,last_error:clean(e.message),error:'queue unreadable'}}}
function readQueue(){return detailed().rows}async function clearQueue(){return withLock(()=>{try{fs.unlinkSync(queuePath());return true}catch(e){if(e.code==='ENOENT')return false;throw e}})}async function pruneQueue(){return withLock(()=>{const d=detailed(),now=Date.now(),s=settings();if(d.errors.length)throw Error('队列损坏');const rows=d.rows.filter(x=>now-(x.created_at||now)<=s.ttl&&Number(x.attempts||0)<s.retries);write(queuePath(),rows);return rows.length})}
async function retryQueue(send,opts={}){return withLock(async()=>{const d=detailed(),s=settings(),now=Date.now(),keep=[],dead=[],wanted=opts.id||null;let sent=0;for(const row of d.rows){if(wanted&&row.key!==wanted){keep.push(row);continue}if(!opts.all&&!wanted&&Number(row.next_retry_at||0)>now){keep.push(row);continue}try{if(await send(row.payload)){sent++;continue}throw Error('remote rejected')}catch(e){row.attempts=Number(row.attempts||0)+1;row.last_error=clean(e.message).slice(0,160);row.next_retry_at=Date.now()+Math.min(3600000,1000*2**Math.min(row.attempts,10));if(row.attempts>=s.retries)dead.push({...row,dead_lettered_at:Date.now()});else keep.push(row)}}write(queuePath(),keep);if(dead.length)write(deadPath(),detailed(deadPath()).rows.concat(dead));return{sent,remaining:keep.length,dead_lettered:dead.length}})}
async function deadLetter(){return withLock(()=>{const d=detailed(),s=settings(),move=d.rows.filter(x=>Number(x.attempts||0)>=s.retries);write(queuePath(),d.rows.filter(x=>!move.includes(x)));if(move.length)write(deadPath(),detailed(deadPath()).rows.concat(move));return move.length})}async function inspect(){return{queue:detailed().rows.map(x=>({id:x.key,event_id:x.payload.event_id,type:x.payload.event,time:x.created_at,attempts:x.attempts,error:x.last_error})),dead_letter:detailed(deadPath()).rows.map(x=>({id:x.key,event_id:x.payload.event_id,type:x.payload.event,time:x.created_at,attempts:x.attempts,error:x.last_error}))}}
module.exports={queuePath,deadPath,safePayload,readQueue,enqueue,summary,clearQueue,pruneQueue,retryQueue,deadLetter,inspect,settings};